// Generated by Rcpp::compileAttributes() - edits will be overwritten

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calculate_effort
double calculate_effort(const std::vector<char>& layout_keys, const std::vector<double>& pos_x, const std::vector<double>& pos_y, const std::vector<int>& pos_row, const std::vector<int>& pos_col, const std::string& text, const std::vector<double>& char_freq, const std::vector<char>& char_list, double w_base, double w_same_finger, double w_same_hand, double w_row_change);
RcppExport SEXP _lbkeyboard_calculate_effort(SEXP layout_keysSEXP, SEXP pos_xSEXP, SEXP pos_ySEXP, SEXP pos_rowSEXP, SEXP pos_colSEXP, SEXP textSEXP, SEXP char_freqSEXP, SEXP char_listSEXP, SEXP w_baseSEXP, SEXP w_same_fingerSEXP, SEXP w_same_handSEXP, SEXP w_row_changeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<char>& >::type layout_keys(layout_keysSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pos_x(pos_xSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type pos_y(pos_ySEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type pos_row(pos_rowSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type pos_col(pos_colSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type text(textSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type char_freq(char_freqSEXP);
    Rcpp::traits::input_parameter< const std::vector<char>& >::type char_list(char_listSEXP);
    Rcpp::traits::input_parameter< double >::type w_base(w_baseSEXP);
    Rcpp::traits::input_parameter< double >::type w_same_finger(w_same_fingerSEXP);
    Rcpp::traits::input_parameter< double >::type w_same_hand(w_same_handSEXP);
    Rcpp::traits::input_parameter< double >::type w_row_change(w_row_changeSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_effort(layout_keys, pos_x, pos_y, pos_row, pos_col, text, char_freq, char_list, w_base, w_same_finger, w_same_hand, w_row_change));
    return rcpp_result_gen;
END_RCPP
}
// optimize_keyboard_layout
List optimize_keyboard_layout(std::vector<char> initial_layout, std::vector<double> pos_x, std::vector<double> pos_y, std::vector<int> pos_row, std::vector<int> pos_col, std::vector<std::string> text_samples, std::vector<double> char_freq, std::vector<char> char_list, int population_size, int generations, double mutation_rate, double crossover_rate, int tournament_size, int elite_count, double w_base, double w_same_finger, double w_same_hand, double w_row_change, bool verbose, std::vector<bool> fixed_positions);
RcppExport SEXP _lbkeyboard_optimize_keyboard_layout(SEXP initial_layoutSEXP, SEXP pos_xSEXP, SEXP pos_ySEXP, SEXP pos_rowSEXP, SEXP pos_colSEXP, SEXP text_samplesSEXP, SEXP char_freqSEXP, SEXP char_listSEXP, SEXP population_sizeSEXP, SEXP generationsSEXP, SEXP mutation_rateSEXP, SEXP crossover_rateSEXP, SEXP tournament_sizeSEXP, SEXP elite_countSEXP, SEXP w_baseSEXP, SEXP w_same_fingerSEXP, SEXP w_same_handSEXP, SEXP w_row_changeSEXP, SEXP verboseSEXP, SEXP fixed_positionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<char> >::type initial_layout(initial_layoutSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type pos_x(pos_xSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type pos_y(pos_ySEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type pos_row(pos_rowSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type pos_col(pos_colSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type text_samples(text_samplesSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type char_freq(char_freqSEXP);
    Rcpp::traits::input_parameter< std::vector<char> >::type char_list(char_listSEXP);
    Rcpp::traits::input_parameter< int >::type population_size(population_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type generations(generationsSEXP);
    Rcpp::traits::input_parameter< double >::type mutation_rate(mutation_rateSEXP);
    Rcpp::traits::input_parameter< double >::type crossover_rate(crossover_rateSEXP);
    Rcpp::traits::input_parameter< int >::type tournament_size(tournament_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type elite_count(elite_countSEXP);
    Rcpp::traits::input_parameter< double >::type w_base(w_baseSEXP);
    Rcpp::traits::input_parameter< double >::type w_same_finger(w_same_fingerSEXP);
    Rcpp::traits::input_parameter< double >::type w_same_hand(w_same_handSEXP);
    Rcpp::traits::input_parameter< double >::type w_row_change(w_row_changeSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< std::vector<bool> >::type fixed_positions(fixed_positionsSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_keyboard_layout(initial_layout, pos_x, pos_y, pos_row, pos_col, text_samples, char_freq, char_list, population_size, generations, mutation_rate, crossover_rate, tournament_size, elite_count, w_base, w_same_finger, w_same_hand, w_row_change, verbose, fixed_positions));
    return rcpp_result_gen;
END_RCPP
}
// layout_effort
double layout_effort(CharacterVector layout, NumericVector pos_x, NumericVector pos_y, IntegerVector pos_row, IntegerVector pos_col, CharacterVector text_samples, NumericVector char_freq, CharacterVector char_list, double w_base, double w_same_finger, double w_same_hand, double w_row_change);
RcppExport SEXP _lbkeyboard_layout_effort(SEXP layoutSEXP, SEXP pos_xSEXP, SEXP pos_ySEXP, SEXP pos_rowSEXP, SEXP pos_colSEXP, SEXP text_samplesSEXP, SEXP char_freqSEXP, SEXP char_listSEXP, SEXP w_baseSEXP, SEXP w_same_fingerSEXP, SEXP w_same_handSEXP, SEXP w_row_changeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type layout(layoutSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pos_x(pos_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pos_y(pos_ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pos_row(pos_rowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pos_col(pos_colSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type text_samples(text_samplesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type char_freq(char_freqSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type char_list(char_listSEXP);
    Rcpp::traits::input_parameter< double >::type w_base(w_baseSEXP);
    Rcpp::traits::input_parameter< double >::type w_same_finger(w_same_fingerSEXP);
    Rcpp::traits::input_parameter< double >::type w_same_hand(w_same_handSEXP);
    Rcpp::traits::input_parameter< double >::type w_row_change(w_row_changeSEXP);
    rcpp_result_gen = Rcpp::wrap(layout_effort(layout, pos_x, pos_y, pos_row, pos_col, text_samples, char_freq, char_list, w_base, w_same_finger, w_same_hand, w_row_change));
    return rcpp_result_gen;
END_RCPP
}
// effort_breakdown
List effort_breakdown(CharacterVector layout, NumericVector pos_x, NumericVector pos_y, IntegerVector pos_row, IntegerVector pos_col, CharacterVector text_samples, NumericVector char_freq, CharacterVector char_list);
RcppExport SEXP _lbkeyboard_effort_breakdown(SEXP layoutSEXP, SEXP pos_xSEXP, SEXP pos_ySEXP, SEXP pos_rowSEXP, SEXP pos_colSEXP, SEXP text_samplesSEXP, SEXP char_freqSEXP, SEXP char_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type layout(layoutSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pos_x(pos_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pos_y(pos_ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pos_row(pos_rowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pos_col(pos_colSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type text_samples(text_samplesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type char_freq(char_freqSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type char_list(char_listSEXP);
    rcpp_result_gen = Rcpp::wrap(effort_breakdown(layout, pos_x, pos_y, pos_row, pos_col, text_samples, char_freq, char_list));
    return rcpp_result_gen;
END_RCPP
}
// random_layout
CharacterVector random_layout(CharacterVector keys);
RcppExport SEXP _lbkeyboard_random_layout(SEXP keysSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type keys(keysSEXP);
    rcpp_result_gen = Rcpp::wrap(random_layout(keys));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lbkeyboard_calculate_effort", (DL_FUNC) &_lbkeyboard_calculate_effort, 12},
    {"_lbkeyboard_optimize_keyboard_layout", (DL_FUNC) &_lbkeyboard_optimize_keyboard_layout, 20},
    {"_lbkeyboard_layout_effort", (DL_FUNC) &_lbkeyboard_layout_effort, 12},
    {"_lbkeyboard_effort_breakdown", (DL_FUNC) &_lbkeyboard_effort_breakdown, 8},
    {"_lbkeyboard_random_layout", (DL_FUNC) &_lbkeyboard_random_layout, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_lbkeyboard(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
