// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// layout_effort
double layout_effort(CharacterVector layout, NumericVector pos_x, NumericVector pos_y, IntegerVector pos_row, IntegerVector pos_col, CharacterVector text_samples, NumericVector char_freq, CharacterVector char_list, double w_base, double w_same_finger, double w_same_hand, double w_row_change, double w_trigram);
RcppExport SEXP _lbkeyboard_layout_effort(SEXP layoutSEXP, SEXP pos_xSEXP, SEXP pos_ySEXP, SEXP pos_rowSEXP, SEXP pos_colSEXP, SEXP text_samplesSEXP, SEXP char_freqSEXP, SEXP char_listSEXP, SEXP w_baseSEXP, SEXP w_same_fingerSEXP, SEXP w_same_handSEXP, SEXP w_row_changeSEXP, SEXP w_trigramSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type layout(layoutSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pos_x(pos_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pos_y(pos_ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pos_row(pos_rowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pos_col(pos_colSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type text_samples(text_samplesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type char_freq(char_freqSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type char_list(char_listSEXP);
    Rcpp::traits::input_parameter< double >::type w_base(w_baseSEXP);
    Rcpp::traits::input_parameter< double >::type w_same_finger(w_same_fingerSEXP);
    Rcpp::traits::input_parameter< double >::type w_same_hand(w_same_handSEXP);
    Rcpp::traits::input_parameter< double >::type w_row_change(w_row_changeSEXP);
    Rcpp::traits::input_parameter< double >::type w_trigram(w_trigramSEXP);
    rcpp_result_gen = Rcpp::wrap(layout_effort(layout, pos_x, pos_y, pos_row, pos_col, text_samples, char_freq, char_list, w_base, w_same_finger, w_same_hand, w_row_change, w_trigram));
    return rcpp_result_gen;
END_RCPP
}
// effort_breakdown
List effort_breakdown(CharacterVector layout, NumericVector pos_x, NumericVector pos_y, IntegerVector pos_row, IntegerVector pos_col, CharacterVector text_samples, NumericVector char_freq, CharacterVector char_list);
RcppExport SEXP _lbkeyboard_effort_breakdown(SEXP layoutSEXP, SEXP pos_xSEXP, SEXP pos_ySEXP, SEXP pos_rowSEXP, SEXP pos_colSEXP, SEXP text_samplesSEXP, SEXP char_freqSEXP, SEXP char_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type layout(layoutSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pos_x(pos_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pos_y(pos_ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pos_row(pos_rowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pos_col(pos_colSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type text_samples(text_samplesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type char_freq(char_freqSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type char_list(char_listSEXP);
    rcpp_result_gen = Rcpp::wrap(effort_breakdown(layout, pos_x, pos_y, pos_row, pos_col, text_samples, char_freq, char_list));
    return rcpp_result_gen;
END_RCPP
}
// random_layout
CharacterVector random_layout(CharacterVector keys);
RcppExport SEXP _lbkeyboard_random_layout(SEXP keysSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type keys(keysSEXP);
    rcpp_result_gen = Rcpp::wrap(random_layout(keys));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lbkeyboard_layout_effort", (DL_FUNC) &_lbkeyboard_layout_effort, 13},
    {"_lbkeyboard_effort_breakdown", (DL_FUNC) &_lbkeyboard_effort_breakdown, 8},
    {"_lbkeyboard_random_layout", (DL_FUNC) &_lbkeyboard_random_layout, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_lbkeyboard(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
