# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

layout_effort <- function(layout, pos_x, pos_y, pos_row, pos_col, text_samples, char_freq, char_list, w_base = 1.0, w_same_finger = 3.0, w_same_hand = 1.0, w_row_change = 0.5, w_trigram = 0.3) {
    .Call(`_lbkeyboard_layout_effort`, layout, pos_x, pos_y, pos_row, pos_col, text_samples, char_freq, char_list, w_base, w_same_finger, w_same_hand, w_row_change, w_trigram)
}

effort_breakdown <- function(layout, pos_x, pos_y, pos_row, pos_col, text_samples, char_freq, char_list) {
    .Call(`_lbkeyboard_effort_breakdown`, layout, pos_x, pos_y, pos_row, pos_col, text_samples, char_freq, char_list)
}

random_layout <- function(keys) {
    .Call(`_lbkeyboard_random_layout`, keys)
}

